{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "6.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.2.7.jar",
          "url": "spring-test-6.2.7.jar",
          "size": 1024651,
          "sha512": "c589a00d02780ed1a2dde1df1d1f75f0ab6697f6b31db7c5b8c715fd4934c257de048c59c0c224412756b4040a74cf85912d56b249263587f16bc960fec354ad",
          "sha256": "7349bcbd17e4295befb5f9e309d14b41abbb1c85714d25312a250d252ce344e4",
          "sha1": "77af0b9d6b218d149f77e63ff5ec6349b5d8abdd",
          "md5": "f439342fa0828e5fefc0b3d350960505"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.2.7.jar",
          "url": "spring-test-6.2.7.jar",
          "size": 1024651,
          "sha512": "c589a00d02780ed1a2dde1df1d1f75f0ab6697f6b31db7c5b8c715fd4934c257de048c59c0c224412756b4040a74cf85912d56b249263587f16bc960fec354ad",
          "sha256": "7349bcbd17e4295befb5f9e309d14b41abbb1c85714d25312a250d252ce344e4",
          "sha1": "77af0b9d6b218d149f77e63ff5ec6349b5d8abdd",
          "md5": "f439342fa0828e5fefc0b3d350960505"
        }
      ]
    }
  ]
}
