{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "6.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.2.7.jar",
          "url": "spring-web-6.2.7.jar",
          "size": 2088910,
          "sha512": "77523f0f3e367850f088af61ae59a108ebfe703d1818b874024b9574c8bdd711c3f1daa9f3ba15b806b2a3ed425c0ee3008058011bf62d0700833457abcc9f35",
          "sha256": "1acf7461fd4127421fc545c43363f9aae0b0a47ad288ca191b0e9ed0252f1000",
          "sha1": "1bd08eba2f2fd69eef49473e42fe124a20e7f844",
          "md5": "58f2791f66abfb506a506340f4482e33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.2.7.jar",
          "url": "spring-web-6.2.7.jar",
          "size": 2088910,
          "sha512": "77523f0f3e367850f088af61ae59a108ebfe703d1818b874024b9574c8bdd711c3f1daa9f3ba15b806b2a3ed425c0ee3008058011bf62d0700833457abcc9f35",
          "sha256": "1acf7461fd4127421fc545c43363f9aae0b0a47ad288ca191b0e9ed0252f1000",
          "sha1": "1bd08eba2f2fd69eef49473e42fe124a20e7f844",
          "md5": "58f2791f66abfb506a506340f4482e33"
        }
      ]
    }
  ]
}
