{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.5.0.jar",
          "url": "spring-boot-starter-json-3.5.0.jar",
          "size": 4746,
          "sha512": "956b3958dde1493a9f12d150b90e821af9b70d65d16a4e64087cf5b6c21944ee0b1ed043ce49b29659805ce7ba514e3d9e6cef281edbcf2f97aa59f37572611f",
          "sha256": "8c2a29b99e0bf83aa5a435e3e14bc22a8b8b57a15af62115d0ad43964974323e",
          "sha1": "af98a526ea3f68c179a6c6199bb1dbe864f43b93",
          "md5": "523f1f1d6dc863650f53d27feceab11d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.5.0.jar",
          "url": "spring-boot-starter-json-3.5.0.jar",
          "size": 4746,
          "sha512": "956b3958dde1493a9f12d150b90e821af9b70d65d16a4e64087cf5b6c21944ee0b1ed043ce49b29659805ce7ba514e3d9e6cef281edbcf2f97aa59f37572611f",
          "sha256": "8c2a29b99e0bf83aa5a435e3e14bc22a8b8b57a15af62115d0ad43964974323e",
          "sha1": "af98a526ea3f68c179a6c6199bb1dbe864f43b93",
          "md5": "523f1f1d6dc863650f53d27feceab11d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.5.0-javadoc.jar",
          "url": "spring-boot-starter-json-3.5.0-javadoc.jar",
          "size": 4746,
          "sha512": "7b00f14cf1ffb9c6b3726bd33c755573b8163b5d27a9d09c0c0a7acfbf4f89548dbca9b8cad53ad9c8de7b803236415accd71de21da00a5fa50655529b1a6b8a",
          "sha256": "686ac36488016adf83318e1d54f128fda4329954604940bc9829b93c4ba64aaf",
          "sha1": "67be056161202c4b12942a326f649c5dcb7c3525",
          "md5": "efcc5a1789ad313188d053707e439e3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.5.0-sources.jar",
          "url": "spring-boot-starter-json-3.5.0-sources.jar",
          "size": 4746,
          "sha512": "7b00f14cf1ffb9c6b3726bd33c755573b8163b5d27a9d09c0c0a7acfbf4f89548dbca9b8cad53ad9c8de7b803236415accd71de21da00a5fa50655529b1a6b8a",
          "sha256": "686ac36488016adf83318e1d54f128fda4329954604940bc9829b93c4ba64aaf",
          "sha1": "67be056161202c4b12942a326f649c5dcb7c3525",
          "md5": "efcc5a1789ad313188d053707e439e3e"
        }
      ]
    }
  ]
}
