{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-tx",
    "version": "6.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.2.7.jar",
          "url": "spring-tx-6.2.7.jar",
          "size": 285385,
          "sha512": "b540e4f8f4b80a081ee0815a17db811e23be46febd698b20db9b03b14ec83308a2f5083c9f9790605e375950ee25307453b65f4b19d97e7334a2805525f394bb",
          "sha256": "58c20096e632333a09d0da33e0c6bf75acbc71c49837ea7d2340663aadf6da25",
          "sha1": "6cf5d200c297fa8cc0b4cf39c1a20b310d2c3d52",
          "md5": "329d6cd5651d74ed90810ee47365ba9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.2.7.jar",
          "url": "spring-tx-6.2.7.jar",
          "size": 285385,
          "sha512": "b540e4f8f4b80a081ee0815a17db811e23be46febd698b20db9b03b14ec83308a2f5083c9f9790605e375950ee25307453b65f4b19d97e7334a2805525f394bb",
          "sha256": "58c20096e632333a09d0da33e0c6bf75acbc71c49837ea7d2340663aadf6da25",
          "sha1": "6cf5d200c297fa8cc0b4cf39c1a20b310d2c3d52",
          "md5": "329d6cd5651d74ed90810ee47365ba9d"
        }
      ]
    }
  ]
}
