{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-core",
    "version": "6.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.2.7.jar",
          "url": "spring-core-6.2.7.jar",
          "size": 1962562,
          "sha512": "fb9cf69241743961442654168d0555014249420515debeff084f747517f1d3078af2b88118e2f4ac000d92f92d25daa92a435e413f49516664330366519b4dd3",
          "sha256": "d7fe31a31ca3ea6226d003999df40153993af6d11e62df5eaf7d5d2b2189a511",
          "sha1": "525a228b8b4323568b7aa9e49c1e1df27838adf1",
          "md5": "a671eff16be00f71823d9aa77baff8e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.2.7.jar",
          "url": "spring-core-6.2.7.jar",
          "size": 1962562,
          "sha512": "fb9cf69241743961442654168d0555014249420515debeff084f747517f1d3078af2b88118e2f4ac000d92f92d25daa92a435e413f49516664330366519b4dd3",
          "sha256": "d7fe31a31ca3ea6226d003999df40153993af6d11e62df5eaf7d5d2b2189a511",
          "sha1": "525a228b8b4323568b7aa9e49c1e1df27838adf1",
          "md5": "a671eff16be00f71823d9aa77baff8e4"
        }
      ]
    }
  ]
}
