{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-parameter-names",
    "version": "2.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.19.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.19.0.jar",
          "url": "jackson-module-parameter-names-2.19.0.jar",
          "size": 10391,
          "sha512": "1323b96ffae5bc5929eb2b3a3c919747868c57dbb9c0fd369f0dd0ad9dca2f7c49b60a8ea5a29e8fea07f5cccd12a4f467320b031e305d568176b10031b40c8d",
          "sha256": "a2ad4f099694b4a7a4a9daaf737e6289cd3d310a438460acaa79bbe4d45bb4bb",
          "sha1": "04963234952362539ca73c85b6a423c851f04f1d",
          "md5": "9afea57e26d8a0d57ce4e0eefe5b6d37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.19.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.19.0.jar",
          "url": "jackson-module-parameter-names-2.19.0.jar",
          "size": 10391,
          "sha512": "1323b96ffae5bc5929eb2b3a3c919747868c57dbb9c0fd369f0dd0ad9dca2f7c49b60a8ea5a29e8fea07f5cccd12a4f467320b031e305d568176b10031b40c8d",
          "sha256": "a2ad4f099694b4a7a4a9daaf737e6289cd3d310a438460acaa79bbe4d45bb4bb",
          "sha1": "04963234952362539ca73c85b6a423c851f04f1d",
          "md5": "9afea57e26d8a0d57ce4e0eefe5b6d37"
        }
      ]
    }
  ]
}
