{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jdbc",
    "version": "6.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-6.2.7.jar",
          "url": "spring-jdbc-6.2.7.jar",
          "size": 472297,
          "sha512": "1af81c3216f92123be7e81d9aa11f58541ba9ef678493f2c8f692628d38624be10a3444317e9363155e390b17585cab831e0b79eaf60da194bbce5daf223c493",
          "sha256": "caac5117c00a56c02b37fcb300f5e0206f2b77a2cfce79c8871ea664c2cf594a",
          "sha1": "9c2a6ac46e3af69b226401678591b6fe0350a617",
          "md5": "cec3cecf370f87431244d39760318578"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-6.2.7.jar",
          "url": "spring-jdbc-6.2.7.jar",
          "size": 472297,
          "sha512": "1af81c3216f92123be7e81d9aa11f58541ba9ef678493f2c8f692628d38624be10a3444317e9363155e390b17585cab831e0b79eaf60da194bbce5daf223c493",
          "sha256": "caac5117c00a56c02b37fcb300f5e0206f2b77a2cfce79c8871ea664c2cf594a",
          "sha1": "9c2a6ac46e3af69b226401678591b6fe0350a617",
          "md5": "cec3cecf370f87431244d39760318578"
        }
      ]
    }
  ]
}
