{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.5.0.jar",
          "url": "spring-boot-test-3.5.0.jar",
          "size": 256567,
          "sha512": "2144365c6248e9d9d7ae850c442413e6ae1417e265062573c2e9dcddb631edaa6f21c49a6b04a9694b5368269f2ae544f6bd20cfeaed3273a70eab1c6ff61802",
          "sha256": "ed41ab43fe9d86b3ed838cb2ffb5f82619c81bff14dc46870c29d63e4f42db4a",
          "sha1": "1c5c19ae32d1c4b8532dcab8a8e92094ef864bda",
          "md5": "f1c45d3286d73b92e648c99149d27593"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.5.0.jar",
          "url": "spring-boot-test-3.5.0.jar",
          "size": 256567,
          "sha512": "2144365c6248e9d9d7ae850c442413e6ae1417e265062573c2e9dcddb631edaa6f21c49a6b04a9694b5368269f2ae544f6bd20cfeaed3273a70eab1c6ff61802",
          "sha256": "ed41ab43fe9d86b3ed838cb2ffb5f82619c81bff14dc46870c29d63e4f42db4a",
          "sha1": "1c5c19ae32d1c4b8532dcab8a8e92094ef864bda",
          "md5": "f1c45d3286d73b92e648c99149d27593"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.5.0-javadoc.jar",
          "url": "spring-boot-test-3.5.0-javadoc.jar",
          "size": 419921,
          "sha512": "c92fd0833cf180dc2c55a6dde9b777d236833e3b205123c2633374fcefb7f2bc9dda56df63f0811f769dc08a6d5c6915713bc55767bbdaececf7752abe2c5f36",
          "sha256": "17d7576264ec7adc5915658e17becbd7e365014455515b334d8c907edf65de7b",
          "sha1": "03ca45ea4598405a548dc55f7500e9d79b7d467e",
          "md5": "daf33f51d007f154076ffba9cdd03f96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.5.0-sources.jar",
          "url": "spring-boot-test-3.5.0-sources.jar",
          "size": 175435,
          "sha512": "14f214dc39a5350b5ddb502dda58ebc6acccf3cdeb58f525148b3cabc4268093ef36a16469195aa5b31f08d92aea75c0633359057110b0ecd9f9805fd05275f8",
          "sha256": "6bffd92e2d5c528294bc9dd00f74e3f40de429fbb7c9be7f62447dc5083c0c2d",
          "sha1": "3c26192e2f8fa6a194c3eb4216e02b44afecbf18",
          "md5": "e6d71621d0f70dd1ea0d84cb196c310f"
        }
      ]
    }
  ]
}
