{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.7.jar",
          "url": "spring-webmvc-6.2.7.jar",
          "size": 1089611,
          "sha512": "dff49bd0c932ba49c8ad0e84009f4c22145c7232dc9a023b367cb378a0dcb8168c0d8b9d26f4fa9fa988ca027c120f04a4cfa9497dadabb6b2914d696a3c85d0",
          "sha256": "50c801768e49fc48c8e92e2d94a803af209ea1f5e3126bd8d7370b5c59b9e71a",
          "sha1": "0a1954b3a51f585c6b8582831661fec981d2571e",
          "md5": "c406f63d85b1ae5239422009a43cc119"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.7.jar",
          "url": "spring-webmvc-6.2.7.jar",
          "size": 1089611,
          "sha512": "dff49bd0c932ba49c8ad0e84009f4c22145c7232dc9a023b367cb378a0dcb8168c0d8b9d26f4fa9fa988ca027c120f04a4cfa9497dadabb6b2914d696a3c85d0",
          "sha256": "50c801768e49fc48c8e92e2d94a803af209ea1f5e3126bd8d7370b5c59b9e71a",
          "sha1": "0a1954b3a51f585c6b8582831661fec981d2571e",
          "md5": "c406f63d85b1ae5239422009a43cc119"
        }
      ]
    }
  ]
}
