{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.5.0.jar",
          "url": "spring-boot-buildpack-platform-3.5.0.jar",
          "size": 318702,
          "sha512": "85d45a4828135465f4c243653345bde9c3f8482b0d692294375f0cf718a9e4fdb429439d9f4edf0cc1fa8e7925c9d5fdae230a4967962e3f9c73b564bfad80fa",
          "sha256": "3f9a9d758765bccf4b3a59c4afd94bc6390b845860aaa3e21b5bf26548e5f1a0",
          "sha1": "523a8532f7bf9119365dc4ccd8e8aff9439b99d1",
          "md5": "f329e335fe4faeb72484a21949a7a3ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.5.0.jar",
          "url": "spring-boot-buildpack-platform-3.5.0.jar",
          "size": 318702,
          "sha512": "85d45a4828135465f4c243653345bde9c3f8482b0d692294375f0cf718a9e4fdb429439d9f4edf0cc1fa8e7925c9d5fdae230a4967962e3f9c73b564bfad80fa",
          "sha256": "3f9a9d758765bccf4b3a59c4afd94bc6390b845860aaa3e21b5bf26548e5f1a0",
          "sha1": "523a8532f7bf9119365dc4ccd8e8aff9439b99d1",
          "md5": "f329e335fe4faeb72484a21949a7a3ab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.5.0-javadoc.jar",
          "url": "spring-boot-buildpack-platform-3.5.0-javadoc.jar",
          "size": 449146,
          "sha512": "8601865a17f4a484470bbe5861875a86a449d4f13030264abf64d984129553c387ac32e8d395ccae00c0b13a380fcbe2e275724c3aabf13723b2abcb045d1ff4",
          "sha256": "f44be92891b7a9e90cfce472337363ceb7b012fadb4059ad299321845a02988e",
          "sha1": "c2778573cbc7c8017b7b65aea374f9e1a46e2ebb",
          "md5": "4f29928e462a662321793b60bc3a9f33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.5.0-sources.jar",
          "url": "spring-boot-buildpack-platform-3.5.0-sources.jar",
          "size": 191323,
          "sha512": "2007207bd16b6d3b3dfa0ff00a5132b63ae27e2d57e764bb7ef2798cf08271830fb4d01d79a9eeb8aaba20d899c38a1b2819c1febf0acd93a935d8246c188a82",
          "sha256": "39c4bf38b639aec7654ca608bd7b2fb98650b582a41e20ef3a03c0dc9d60f76f",
          "sha1": "01953ce827d56973d753d375c5c0cc95139a39af",
          "md5": "8f52c4945658963f5965acbb68df0b1b"
        }
      ]
    }
  ]
}
