{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.41"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.5.0.jar",
          "url": "spring-boot-starter-tomcat-3.5.0.jar",
          "size": 4791,
          "sha512": "f0412e374b5452a35b94f9c9c183bc148fb2fd894762b283f0b805582a75f7960aa2564df93264d29e9f18834962556e7ed1f9ac20a0ceb69679807d39955876",
          "sha256": "9b9ef4dc3b3b1d6c9f4c072f135641cad8ab658002d12b2f0f485fab952e5cd3",
          "sha1": "2e22a33e6f9444a7248581a23541fea5c1f6c216",
          "md5": "21242b57690dc98faf6583a726434c20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.41"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.5.0.jar",
          "url": "spring-boot-starter-tomcat-3.5.0.jar",
          "size": 4791,
          "sha512": "f0412e374b5452a35b94f9c9c183bc148fb2fd894762b283f0b805582a75f7960aa2564df93264d29e9f18834962556e7ed1f9ac20a0ceb69679807d39955876",
          "sha256": "9b9ef4dc3b3b1d6c9f4c072f135641cad8ab658002d12b2f0f485fab952e5cd3",
          "sha1": "2e22a33e6f9444a7248581a23541fea5c1f6c216",
          "md5": "21242b57690dc98faf6583a726434c20"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.5.0-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.5.0-javadoc.jar",
          "size": 4791,
          "sha512": "039c5f37ebab207a3212962d8417bdbdb150d7f13a7499fa2b87d9df591c7e0141efa1435d5c231c199b07d2102d44f89d30dfa2c9ce66e1cdd3eabf2a1f4d61",
          "sha256": "db76ddb9ad1ba22f02f085897a599fa2dcb2300c0fbd509ae5eb1d66162f675e",
          "sha1": "6d793a074843ba4e7a3e0b9ad8615460d45174d2",
          "md5": "2f075f03c3cbf096625aaad1e1e44b01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.5.0-sources.jar",
          "url": "spring-boot-starter-tomcat-3.5.0-sources.jar",
          "size": 4791,
          "sha512": "039c5f37ebab207a3212962d8417bdbdb150d7f13a7499fa2b87d9df591c7e0141efa1435d5c231c199b07d2102d44f89d30dfa2c9ce66e1cdd3eabf2a1f4d61",
          "sha256": "db76ddb9ad1ba22f02f085897a599fa2dcb2300c0fbd509ae5eb1d66162f675e",
          "sha1": "6d793a074843ba4e7a3e0b9ad8615460d45174d2",
          "md5": "2f075f03c3cbf096625aaad1e1e44b01"
        }
      ]
    }
  ]
}
