{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.5.0.jar",
          "url": "spring-boot-starter-logging-3.5.0.jar",
          "size": 4756,
          "sha512": "b95bd2caa53c32615de65117b4d552a81346b74305a01778aa2908a8ffdbff315fdc7fa398978a38d673b2c39ed33b99bd4775a58e8e21a7d7395536b084f791",
          "sha256": "e70f5c421a78f38c3308b83e4d774e0267314ebe6daa5f6eb3b09480772e4e41",
          "sha1": "7db0461d8895f00a9841bf5558501fe90e7eba4c",
          "md5": "9112a867eec8f7cc92a3cf743c7a5d26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.5.0.jar",
          "url": "spring-boot-starter-logging-3.5.0.jar",
          "size": 4756,
          "sha512": "b95bd2caa53c32615de65117b4d552a81346b74305a01778aa2908a8ffdbff315fdc7fa398978a38d673b2c39ed33b99bd4775a58e8e21a7d7395536b084f791",
          "sha256": "e70f5c421a78f38c3308b83e4d774e0267314ebe6daa5f6eb3b09480772e4e41",
          "sha1": "7db0461d8895f00a9841bf5558501fe90e7eba4c",
          "md5": "9112a867eec8f7cc92a3cf743c7a5d26"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.5.0-javadoc.jar",
          "url": "spring-boot-starter-logging-3.5.0-javadoc.jar",
          "size": 4756,
          "sha512": "7d1950a6cfb05df1568935b326d737281cc72be1cb006a3afd0ea2cfb198185cb02b17c681b9a481510473ca9cc1e66affd3946332dacef931205bd4d194cee5",
          "sha256": "32f04df71e2cd6cc8b6cd43892c5927748e9b1740b894d5f8c9251afbaeaca9e",
          "sha1": "2447faa79f324f2251aaad97adc958b8aad81c38",
          "md5": "5e50d4c39310b205d6dacd1784811658"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.5.0-sources.jar",
          "url": "spring-boot-starter-logging-3.5.0-sources.jar",
          "size": 4756,
          "sha512": "7d1950a6cfb05df1568935b326d737281cc72be1cb006a3afd0ea2cfb198185cb02b17c681b9a481510473ca9cc1e66affd3946332dacef931205bd4d194cee5",
          "sha256": "32f04df71e2cd6cc8b6cd43892c5927748e9b1740b894d5f8c9251afbaeaca9e",
          "sha1": "2447faa79f324f2251aaad97adc958b8aad81c38",
          "md5": "5e50d4c39310b205d6dacd1784811658"
        }
      ]
    }
  ]
}
