apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bento?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei
  SPRING_DATASOURCE_USERNAME: bento
  APP_MAIL_MODE: mock
  APP_MAIL_FROM: dev-mail@lovius.local
  APP_MAIL_SMTP_HOST: smtp.gmail.com
  APP_MAIL_SMTP_PORT: "587"
  APP_MAIL_SMTP_AUTH: "true"
  APP_MAIL_SMTP_STARTTLS: "true"
  APP_PDF_FONT_PATH: /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc
