{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.5.0.jar",
          "url": "spring-boot-starter-web-3.5.0.jar",
          "size": 4802,
          "sha512": "98209620479711a59a712b1f67d8dcf1bff3d4cc122d03296bfbdaae15f9b1633b2cb0f46ed4d8f31e951cbdde06f14ee2da090f666d8b50e8fc846fe05e6bfc",
          "sha256": "31e44bbb76057ecfda11f27140894edfabf56753e6c814b3a98665c79bdc83e2",
          "sha1": "29c6198f7e5cd7c4b9a27045d93879e161d6cdd0",
          "md5": "17c05dae69ffaae8870ab95eb9ff8457"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.5.0.jar",
          "url": "spring-boot-starter-web-3.5.0.jar",
          "size": 4802,
          "sha512": "98209620479711a59a712b1f67d8dcf1bff3d4cc122d03296bfbdaae15f9b1633b2cb0f46ed4d8f31e951cbdde06f14ee2da090f666d8b50e8fc846fe05e6bfc",
          "sha256": "31e44bbb76057ecfda11f27140894edfabf56753e6c814b3a98665c79bdc83e2",
          "sha1": "29c6198f7e5cd7c4b9a27045d93879e161d6cdd0",
          "md5": "17c05dae69ffaae8870ab95eb9ff8457"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.5.0-javadoc.jar",
          "url": "spring-boot-starter-web-3.5.0-javadoc.jar",
          "size": 4802,
          "sha512": "adeb4f88a23d7221c5848acbfff9101963ea73f0a4eea4b0b6c497b7e4df59bbccaa1398df10dac79c286cd126be66f60b84289ea150e9acc8833400f0d3cb6e",
          "sha256": "72a9483d03deb644ff843253981f3b95573e102ea4d467cc970b1b9a7bf7af73",
          "sha1": "98a840b2ed9d81fb7c55b828d1de791bb4522ecf",
          "md5": "afd240d91a1b4ffb003a48aa1c997444"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.5.0-sources.jar",
          "url": "spring-boot-starter-web-3.5.0-sources.jar",
          "size": 4802,
          "sha512": "adeb4f88a23d7221c5848acbfff9101963ea73f0a4eea4b0b6c497b7e4df59bbccaa1398df10dac79c286cd126be66f60b84289ea150e9acc8833400f0d3cb6e",
          "sha256": "72a9483d03deb644ff843253981f3b95573e102ea4d467cc970b1b9a7bf7af73",
          "sha1": "98a840b2ed9d81fb7c55b828d1de791bb4522ecf",
          "md5": "afd240d91a1b4ffb003a48aa1c997444"
        }
      ]
    }
  ]
}
